# fly.toml app configuration file generated for two-four-kay on 2023-05-29T11:56:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "two-four-kay"
primary_region = "lhr"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
